### ISSUE TITLE
Missing OTAnalytics.bat

### ISSUE THREAD

**Issue by hsefati** [OpenTrafficCam/OTAnalytics#100]
According to the documentation [here](https://opentrafficcam.org/OTAnalytics/gettingstarted/installation/#if-you-encounter-problems)
there should be bat file to run the software. However it is not to be find ( or the documentation is not up-to-date)

**Comment by frunika** [comment]
Hi @hsefati, thank you for you issue.
That's definitely an issue in the documentation.
The current prototype is developed in branch `first-version`. You can download the latest prototype here:
https://github.com/OpenTrafficCam/OTAnalytics/archive/refs/heads/first-version.zip

I will change the documentation.

Note:
We are currently working on a complete refactoring of OTAnalytics, which will be released in the next months.

**Comment by Vien06** [comment]
Good day, would I be able to have a working version with the graphical interface for OTAnalytics ? I tried installing the above version but got this error. 

Thank you very much

![image](https://user-images.githubusercontent.com/113410921/228092019-4bf87724-7f8d-4b65-9c32-cd71af892f7b.png)

**Comment by frunika** [comment]
I'll close this issue, since the documentation is fixed.
@Vien06 could you please open a new issue if you still encounter problems?
