### ISSUE TITLE
OTAnalytics.bat not found 

### ISSUE THREAD

**Issue by Vien06** [OpenTrafficCam/OTAnalytics#115]
Good day, 

I'm trying to install the OTAnalytics and run the graphic interface. I cant seem to locate the OTAnalytics.bat. Your help is greatly appreciated. 

Thank you! 
![image](https://user-images.githubusercontent.com/113410921/228089951-7d0b2e8f-28f1-4da9-a875-5fe450cac75d.png)
![image](https://user-images.githubusercontent.com/113410921/228090026-85dc0f2a-78af-4604-91fc-a34570af9840.png)

**Comment by frunika** [comment]
Hi,

as you already noticed, #100 addresses the same problem.
