### ISSUE TITLE
ERROR: GDAL-3.2.3-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by Vien06** [OpenTrafficCam/OTAnalytics#156]
Im using the first version of OTAnalytics , I had the error above when running the install bat. I'm currently using Python 10.0.0 

I'm really trying to use OTVision and OTAnalytics for my thesis but I'm having a hard time running both python software. I tried to fix error lines but I'm going nowhere. Would there be anyone I contact to help me out to run the software. 

Thank you 
![image](https://user-images.githubusercontent.com/113410921/233591052-3c2a484a-4ef9-45d3-926e-68ec8eefbce6.png)

**Comment by randy-seng** [comment]
Hello @Vien06,
apologies for the late reply. The first version of OTAnalytics requires Python 3.9. Please try again after installing python 3.9.

**Comment by martinbaerwolff** [comment]
Hi @Vien06, I hope switching to python 3.9 for the `first_version` branch helped you.

Also, we plan to soon release a completely refactored, stable version of OTAnalytics.

I am closing this issue for now, please reopen, if this is still a problem to you.
