### ISSUE TITLE
Load corresponding tracks to imported video

### ISSUE THREAD

**Issue by hgoerner** [OpenTrafficCam/OTAnalytics#23]
when video is imported the programm automaticaly finds corrsponding track-data

**Comment by frunika** [comment]
closed?
We should have a discussion about data organization.

**Comment by hgoerner** [comment]
Not closed.

Discussion is needed.

**Comment by hgoerner** [comment]
When video is imported: => search for track and flowfile with regex and name from video in paths using os.walk
user gets information that files do exists and can deside to import files.
