### ISSUE TITLE
Create movement using created detectors

### ISSUE THREAD

**Issue by hgoerner** [OpenTrafficCam/OTAnalytics#28]
- [x] list with movements
- [x] Nested dictionary: Movement GateID, GateID
- [x] ordered dictionary
- [x] load movements
- [ ] hash timestamp

**Comment by hgoerner** [comment]
load_movements needs to 
- [ ] draw on canvas
- [ ] fill detectors listboxes

**Comment by frunika** [comment]
The issue title is kind of irritating :D
