### ISSUE TITLE
OTA crashes at loading the tracks of the test video

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTAnalytics#285]
Loaded the newest version of OTA main. Installation and loading the start window worked fine. Tried to load the "Testvideo_Cars-Cyclist_FR20_2020-01-01_00-00-00.ottrk". After a second the loading occured and the image of Radeberg gets loaded. A sec later the windows and the cmd closes, so the program crashed? No error message occured in cmd.
![grafik](https://github.com/OpenTrafficCam/OTAnalytics/assets/73596011/b57f5fbe-d16b-4b3a-bca6-702210e7834f)

Same happens even if I enter a name and a date.
Python: 3.11.4
Recloned and Reinstalled OTA already.

No error or crash with "Sample_FR20_2020-01-01_00-00-00.ottrk", but obviously no picture shown.

**Comment by briemla** [comment]
Thank you for the bug report. We will have a look at it. Given the terminal screenshot, I assume the error occurred on windows. Which version do you use? Windows 10 or 11?

**Comment by arminkollascheck** [comment]
Windows 10

**Comment by arminkollascheck** [comment]
Works now with the newest version.
