### ISSUE TITLE
Function for converting tracks in a displayable format

### ISSUE THREAD

**Issue by hgoerner** [OpenTrafficCam/OTAnalytics#32]

**Comment by martinbaerwolff** [comment]
Duplicate of this: https://github.com/OpenTrafficCam/OTVision/issues/89

**Comment by martinbaerwolff** [comment]
@hgoerner , pls add a also one of the Labels "idea", "bug", "feature" or "question" next time :)

**Comment by hgoerner** [comment]
coordinates of detections gets matched with object in a seperated dictionary. This dictionary include class and coordinates of the object which can be displayed with opencv on tkinter canvas.
