### ISSUE TITLE
Events in the exported otevents have all "section_id:null"

### ISSUE THREAD

**Issue by arminkollascheck** [OpenTrafficCam/OTAnalytics#421]
I tested the main version with the first 4 videos and 4 ottrk of https://github.com/platomo/OpenTrafficCam-testdata/releases 12:00:00. If I press Export eventlist as otevent, I get many events in the eventlist, but every event has "section_id:null" (looked into it by unpacking and Editor). It didnt matter if I used the otflow of the release testdata or my own gates. Excel output is also emptry for the section_id.

Windows 10

Downloaded the main version as zip, used installed.cmd and start_gui.cmd

**Comment by arminkollascheck** [comment]
I wanted to test my OTGroundTruther my loading the otevent file and it didnt work. That was the reason for my work with OTA.

**Comment by randy-seng** [comment]
@arminkollascheck I was not able to reproduce the bug with the latest main. I created the event list using the first four files. The section ids for `section-enter` and `section-leave` events were different than `null`. Could you please check if it works for you?

> I wanted to test my OTGroundTruther my loading the otevent file and it didnt work. That was the reason for my work with OTA.

**Comment by arminkollascheck** [comment]
I just didnt know that there are also scene events in the otevent file and therefore was surpised by the section=null in some events.
I fixed it in the loading of the otevents in the OTGroundTruther. Scene events and section leave events are getting ignored now.
