### ISSUE TITLE
Draw detectors on top of all elements

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTAnalytics#59]
```
    # TODO: Draw detectors on top of all elements
```

https://github.com/OpenTrafficCam/OTAnalytics/blob/c66d0111fcae3264e6e1bf173bb87a34417b2093/OTAnalytics/image_alteration.py#L36

Currently tracks are on top, if I draw counters when tracks are displayed, I cant see them very well.

**Comment by hgoerner** [comment]
detectors are now drawn on top of tracks
