### ISSUE TITLE
Function to automatically create movements from all selected sections

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTAnalytics#65]
- [x] Add a function to automatically create all possible movements (all combinations of orders of two sections) from all selected sections and fill them with the respective sections in the respective order.
- [x] Connect them to a new button in the gui.

**Comment by hgoerner** [comment]
new button autofill => creates window with treeview of all section. Movements get created from all selected sections. Checks for duiplicates is implemented so now movementes are redundant.
