### ISSUE TITLE
Prevent duplicate section names

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTAnalytics#67]
https://github.com/OpenTrafficCam/OTAnalytics/blob/c66d0111fcae3264e6e1bf173bb87a34417b2093/OTAnalytics/main.py#L658

- [x] Check if duplicate
- [x] If duplicate: Warning popup: "Section name already taken, please entry other"
- [ ] Read section name from toplevel entry again

**Comment by hgoerner** [comment]
warning message pops up if either section or movement name already exists
