### ISSUE TITLE
High resolution videos displayed cropped

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTAnalytics#68]
## Problem

High resolution videos (e.g. drone footage) are being cropped in the video player:

![OTAnalytics_video_size](https://user-images.githubusercontent.com/53005443/155489343-4093125e-9db1-4ab8-9851-e540ef5e728c.PNG)

## Proposed solution

Resize video player if video + ( OTAnalytics interface > screen )

**Comment by hgoerner** [comment]
Fix:

- Height of video gets rezised to 800 so GUI doesnt explode / Width gets resized with factor
- Trajectories and bounding boxes + annotation get computed with global resize factor
