### ISSUE TITLE
Enable new tracks with new video

### ISSUE THREAD

**Issue by martinbaerwolff** [OpenTrafficCam/OTAnalytics#78]
Currently I have to restart the whole tool to add new tracks after adding a new video.

We would need a button to remove the tracks. 

Additionally, I think you can automatically "unload" tracks after the corresponding video is removed. I can imagine very few use cases where keeping the tracks after removing the corresponding video makes sense.

**Comment by hgoerner** [comment]
-[x] loading/deloading trackfile
-[x] when video is removed, trackfile gets deleted as well
